[options]
addons_path = /Users/maruti/Documents/TSGit/odoo19/odoo/addons,/Users/maruti/Documents/TSGit/odoo19/odoo/custom-addons
data_dir = /Users/maruti/Documents/TSGit/odoo19/odoo/.odoo-data
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
xmlrpc_port = 8069
log_level = info
dev_mode = reload,qweb,xm
admin_passwd = odoo19

# Odoo Master Password: odoo19
