{
    "name": "Newsletter Compliance",
    "summary": "Consent and suppression governance for Odoo Email Marketing",
    "version": "19.0.1.0.0",
    "category": "Marketing/Email Marketing",
    "license": "LGPL-3",
    "author": "Your Organization",

    "depends": [
        "base",
        "contacts",
        "mail",
        "mass_mailing",
    ],

    "data": [
        "security/newsletter_compliance_groups.xml",
        "security/ir.model.access.csv",
        "security/newsletter_compliance_rules.xml",

        "data/sequences.xml",
        "data/suppression_reason_data.xml",
        "data/campaign_sequences.xml",
        "data/campaign_run_sequences.xml",
        "data/execution_sequences.xml",
        "data/dispatch_cron.xml",
        "data/delivery_sequences.xml",
        "data/delivery_cron.xml",
        "data/retention_sequences.xml",
        "data/retention_policy_data.xml",
        "data/retention_cron.xml",
        "data/monitoring_cron.xml",
        "data/consent_cron.xml",

        "wizard/withdraw_consent_views.xml",
        "wizard/reinstate_suppression_views.xml",
        "wizard/reject_campaign_views.xml",
        "wizard/reset_campaign_views.xml",
        "wizard/cancel_campaign_views.xml",
        "wizard/cancel_execution_views.xml",
        "wizard/suspend_execution_views.xml",
        "wizard/resume_execution_views.xml",
        "wizard/retention_preview_wizard_views.xml",
        "wizard/manual_retention_wizard_views.xml",
        "wizard/legal_hold_release_wizard_views.xml",
        "wizard/privacy_request_execute_wizard_views.xml",
        "wizard/audit_export_wizard_views.xml",

        "views/consent_purpose_views.xml",
        "views/consent_record_views.xml",
        "views/suppression_reason_views.xml",
        "views/suppression_entry_views.xml",
        "views/res_partner_views.xml",
        "views/campaign_brand_views.xml",
        "views/campaign_approval_views.xml",
        "views/send_event_views.xml",
        "views/campaign_archive_views.xml",
        "views/campaign_outcome_views.xml",
        "views/provider_event_views.xml",
        "views/delivery_reputation_views.xml",
        "views/compliance_alert_views.xml",
        "views/provider_health_views.xml",
        "views/res_config_settings_views.xml",
        "views/campaign_run_views.xml",
        "views/recipient_eligibility_views.xml",
        "views/mailing_mailing_views.xml",
        "views/retention_policy_views.xml",
        "views/retention_action_views.xml",
        "views/legal_hold_views.xml",
        "views/privacy_request_views.xml",
        "views/audit_export_views.xml",
        "views/dashboard_views.xml",
        "views/menu_views.xml",
    ],

    "application": False,
    "installable": True,
    "auto_install": False,
}
